/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.Date;
import javamainclass.appointment;
import javamainclass.appointmenthistory;
import javamainclass.cars;
import javamainclass.carsdata;
import javamainclass.patient;
import javamainclass.patienthistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanik
 */
public class Appointment extends javax.swing.JPanel {
    carsdata data;
    appointmenthistory appointmenthistory;
    patienthistory PatientHistory;

    /**
     * Creates new form Appointment
     */
    public Appointment(carsdata data,appointmenthistory appointmenthistory, patienthistory PatientHistory) {
        initComponents();
        this.data = data;
        this.appointmenthistory = appointmenthistory;
        this.PatientHistory = PatientHistory;
        
        
    }
//    public void populatetblpatient() {
//        DefaultTableModel model = (DefaultTableModel)PersonHistoryTBT.getModel();
//        model.setRowCount(0);
//        
//        for (cars c : data.getData()) {
//            Object[] row =new Object[3];
//            row[0]=c;
//            row[1]=c.getAge();
//            row[2]=c.getGender();
//            
//            model.addRow(row);
//        }
//    }
//    public void populatetblappointment(){
//        int selectRowIndex = PersonHistoryTBT.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel)PatientHistory_TBT.getModel();
//        model.setRowCount(0);
//        
//        for (cars c : data.getData()){
//            for (appointment a : appointmenthistory.getappointmenthistory()){
//                if(c.getName().equals(a.getPatient())){
//                    //System.out.println(a.getDatetime());
//                    Object[] row =new Object[1];
//                    row[0]= a.getDatetime();
//                    
//                    model.addRow(row);
//                }
//            }
//        }
//    }
    
//    public void savemethod() {
//            String PatientName = txt_appointmentID.getText();
//            Date appointment_time = jDateChooser1.getDate();
//            
//            appointment a =appointmenthistory.addNewappointment();
//            
//            a.setPatient(PatientName);
//            a.setDatetime(appointment_time);
//            
//           // System.out.println(a.getDatetime());
//            JOptionPane.showMessageDialog(this,"New Appointment Booked");
//            txt_appointmentID.setText("");
//            jDateChooser1.setDate(null);
//            
//            //JOptionPane.showMessageDialog(this,"Appointment has benn booked");
//            
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PersonHistoryTBT = new javax.swing.JTable();
        btnviewapp = new javax.swing.JButton();
        lblpatientname = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        txt_appointmentID = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnaddapp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientHistory_TBT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_patientID = new javax.swing.JLabel();
        txt_Patient_name = new javax.swing.JLabel();
        txt_age = new javax.swing.JLabel();
        txt_gender = new javax.swing.JLabel();
        txt_house = new javax.swing.JLabel();
        txt_city = new javax.swing.JLabel();
        txt_community = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_upperbp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_lowerbp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_heartrate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        PersonHistoryTBT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Age", "Gender", "House", "Community", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PersonHistoryTBT);

        btnviewapp.setText("View Appointments");
        btnviewapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewappActionPerformed(evt);
            }
        });

        lblpatientname.setText("Patient Name:");

        lbldate.setText("Appointment Date:");

        txt_appointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_appointmentIDActionPerformed(evt);
            }
        });

        btnaddapp.setText("Add Appointment");
        btnaddapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddappActionPerformed(evt);
            }
        });

        PatientHistory_TBT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient ID", "Medical Record Number", "Diabetic"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PatientHistory_TBT);

        jLabel2.setText("Age:");

        jLabel3.setText("Gender:");

        jLabel4.setText("House:");

        jLabel5.setText("Community:");

        jLabel6.setText("City:");

        jLabel7.setText("Person Id:");

        txt_Patient_name.setText("jLabel8");

        txt_age.setText("jLabel8");

        txt_gender.setText("jLabel8");

        txt_house.setText("jLabel8");

        txt_city.setText("jLabel8");

        txt_community.setText("jLabel8");

        jLabel16.setText("Appointment Id:");

        jLabel17.setText("upper_limit blood pressure:");

        jLabel18.setText("lower_limit blood pressure:");

        jLabel19.setText("heart_rate:");

        jButton1.setText("Person details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCHEDULE DOCTOR APPOINTMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(lblpatientname)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Patient_name)
                                    .addComponent(txt_age)
                                    .addComponent(txt_house)
                                    .addComponent(txt_gender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(176, 176, 176))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(44, 44, 44))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(35, 35, 35)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_upperbp, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_lowerbp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_appointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txt_heartrate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_patientID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_community)
                                    .addComponent(txt_city))
                                .addGap(0, 529, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnviewapp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnaddapp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewapp)
                    .addComponent(btnaddapp)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_appointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_patientID)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpatientname)
                            .addComponent(txt_Patient_name))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_house))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_city))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_community)
                            .addComponent(jLabel5))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_upperbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addComponent(lbldate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lowerbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_heartrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_appointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_appointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_appointmentIDActionPerformed

    private void btnaddappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddappActionPerformed
        // TODO add your handling code here:
        String patientID = txt_patientID.getText();
        String appointmentID = txt_appointmentID.getText();
        Date appointment_date = jDateChooser1.getDate();
        int upper_limit_bp = Integer.parseInt(txt_upperbp.getText());
        int lower_limit_bp = Integer.parseInt(txt_lowerbp.getText());
        int heart_rate = Integer.parseInt(txt_heartrate.getText());
        
        appointment a = appointmenthistory.addNewappointment();
        
        a.setPatientID(patientID);
        a.setAppointmentID(appointmentID);
        a.setDatetime(appointment_date);
        a.setLowerlimit_bloodPressure(lower_limit_bp);
        a.setUpperlimit_bloodPressure(upper_limit_bp);
        a.setHeart_rate(heart_rate);
        
        JOptionPane.showMessageDialog(this, "Apppointment booked!");
        
        //a.setPatientID(patientID);
        txt_appointmentID.setText("");
        jDateChooser1.setDate(null);
        txt_lowerbp.setText("");
        txt_upperbp.setText("");
        txt_heartrate.setText("");
        
       
    }//GEN-LAST:event_btnaddappActionPerformed

    private void btnviewappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewappActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = PersonHistoryTBT.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Select a row to view all details");
            
        }
        else{
        DefaultTableModel model = (DefaultTableModel)PersonHistoryTBT.getModel();
        cars selectedperson = (cars)model.getValueAt(selectedRowIndex,0);
        
        String age = String.valueOf(selectedperson.getAge());
        txt_patientID.setText(selectedperson.getPersonID());
        txt_Patient_name.setText(selectedperson.getName());
        txt_age.setText(age);
        txt_gender.setText(selectedperson.getGender());
        txt_house.setText(selectedperson.getHouse());
        txt_community.setText(selectedperson.getCommunity());
        txt_city.setText(selectedperson.getCity());
        }
    }//GEN-LAST:event_btnviewappActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed
 public void populateTable(){
     DefaultTableModel model = (DefaultTableModel)PersonHistoryTBT.getModel();
     model.setRowCount(0);
     
     for(cars c : data.getData()){
         
         Object[] row =new Object[7];
            row[0]=c;
            row[1]=c.getName();
            row[2]=c.getAge();
            row[3]=c.getGender();
            row[4]=c.getHouse();
            row[5]=c.getCommunity();
            row[6]=c.getCity();
            
            model.addRow(row);
            
            
         
     }
     
     DefaultTableModel modelPat = (DefaultTableModel)PatientHistory_TBT.getModel();
     modelPat.setRowCount(0);
     
     for(patient p : PatientHistory.getPatienthistory()){
         
         Object[] row =new Object[7];
            row[0]=p;
            row[1]=p.getMedicalRecord();
            row[2]=p.getDiabetic();
            
            
            
            modelPat.addRow(row);
            
            
         
     }
     
     
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PatientHistory_TBT;
    private javax.swing.JTable PersonHistoryTBT;
    private javax.swing.JButton btnaddapp;
    private javax.swing.JButton btnviewapp;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblpatientname;
    private javax.swing.JLabel txt_Patient_name;
    private javax.swing.JLabel txt_age;
    private javax.swing.JTextField txt_appointmentID;
    private javax.swing.JLabel txt_city;
    private javax.swing.JLabel txt_community;
    private javax.swing.JLabel txt_gender;
    private javax.swing.JTextField txt_heartrate;
    private javax.swing.JLabel txt_house;
    private javax.swing.JTextField txt_lowerbp;
    private javax.swing.JLabel txt_patientID;
    private javax.swing.JTextField txt_upperbp;
    // End of variables declaration//GEN-END:variables
}
