/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import java.text.SimpleDateFormat;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javamainclass.cars;
import javamainclass.carsdata;


/**
 * 
 * @author sanik
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    carsdata data;
    static int stamp;
    public ViewPanel(carsdata data) {
        initComponents();
        this.data=data;
        
        populateTable();
        
    }

    public void fillTable(){
        DefaultTableModel model = (DefaultTableModel)tablecars.getModel();
        model.setRowCount(0);
        
        for (cars c : data.getData()){
            Object [] row = new Object [5];
            row[0]=c;
            row[1]=c.getLocation();
            row[2]=c.getAddress();
            row[3]=c.getAge();
            row[4]=c.getGender();
           
        model.addRow(row);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txthouse = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtcommunity = new javax.swing.JTextField();
        lblmanufacturer = new javax.swing.JLabel();
        lblmanufactureryr = new javax.swing.JLabel();
        lblseats = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecars = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        lblmanu = new javax.swing.JLabel();
        lblmanuyr = new javax.swing.JLabel();
        lblseatss = new javax.swing.JLabel();
        lblcolour = new javax.swing.JLabel();
        lblmaintain = new javax.swing.JLabel();
        lblplatee = new javax.swing.JLabel();
        lblloc = new javax.swing.JLabel();
        lblavaila = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_CITY = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpersonid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        txthouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthouseActionPerformed(evt);
            }
        });
        txthouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthouseKeyReleased(evt);
            }
        });

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        txtcommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcommunityActionPerformed(evt);
            }
        });
        txtcommunity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcommunityKeyReleased(evt);
            }
        });

        lblmanufacturer.setText("ADDRESS");

        lblmanufactureryr.setText("AGE");

        lblseats.setText("COMMUNITY");

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        tablecars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PERSON ID", "NAME", "AGE", "GENDER", "ADDRESS", "COMMUNITY", "CITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablecars);

        btnupdate.setText("UPDATE");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnupdateMousePressed(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lblname.setForeground(new java.awt.Color(255, 0, 51));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel1.setText("CITY");

        txt_CITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CITYActionPerformed(evt);
            }
        });

        editbtn.setText("VIEW");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("PERSON ID");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtpersonid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonidActionPerformed(evt);
            }
        });

        jLabel4.setText("NAME");

        jLabel5.setText("GENDER");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcommunity)
                                    .addComponent(txtage)
                                    .addComponent(txt_CITY)
                                    .addComponent(txtgender, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                .addGap(340, 340, 340))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblmanufactureryr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblmanufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txthouse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnupdate)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(editbtn)))
                                .addGap(60, 60, 60)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblcolour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmanu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmanuyr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblseatss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmaintain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblplatee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblloc, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblavaila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate)
                            .addComponent(btn_delete)
                            .addComponent(editbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmanu, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmanuyr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblseatss, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblcolour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblmaintain, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblplatee, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpersonid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmanufacturer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmanufactureryr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblseats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblavaila, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblloc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtcommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcommunityActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablecars.getSelectedRow();
        if (selectedRow<0){
            JOptionPane.showMessageDialog(this,"Select a row to update details");
            return;
        }
        
        
        
        if ( txthouse.getText().length()<=0 || txtcommunity.getText().length()<=0 ||  txtage.getText().length()<=0 || txt_CITY.getText().length()<=0 || txtpersonid.getText().length()<0)
        {   
            JOptionPane.showMessageDialog(this,"One of more field are empty"); 
           
        }
    else
        {
            DefaultTableModel model = (DefaultTableModel)tablecars.getModel();
            cars selecteddetails = (cars) model.getValueAt(selectedRow,0);
            data.deletecars(selecteddetails);
            populateTable();
            //String personID = model.getValueAt(selectedRow, 0).toString();
            
            String id =txtpersonid.getText();
            String name=txtname.getText();
            String address = txthouse.getText();
            int age=Integer.parseInt(txtage.getText());
            String community=txtcommunity.getText();
            String gender=txtgender.getText();
            String city=txt_CITY.getText();
            
            cars c=data.addNewcar();
            c.setPersonID(id);
            c.setAge(age);
            c.setCity(city);
            c.setCommunity(community);
            c.setGender(gender);
            c.setHouse(name);
            c.setLocation(city);
            c.setName(name);
            
                    
        
//                c.getPersonID() == personID;
//                c.setAge(Integer.parseInt(txtage.getText()));
//                c.setHouse(txthouse.getText());
//                c.setCommunity(txtcommunity.getText());
//                c.setCity(txt_CITY.getText());
            
        
        
        populateTable();
//            data.deletecars(selectedcars);
//            fillTable();
//            


//            SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
//             
//            
//            //cars c=data.addNewcar();
//            txtname.setText(String.valueOf(selectedcars.getName()));
//            //c.setName(txtname.getText());
//            txthouse.setText(String.valueOf(selectedcars.getHouse()));
//            txtage.setText(String.valueOf(selectedcars.getAge()));
//            txtcommunity.setText(String.valueOf(selectedcars.getCommunity()));
//            txtgender.setText(String.valueOf(selectedcars.getGender()));
//            txt_CITY.setText(String.valueOf(selectedcars.getCity()));
//            txtgender.setText(String.valueOf(selectedcars.getGender()));
//            c.setAddress(txtaddress.getText());
//            c.setAge(age);
//            c.setLocation(community);
//            c.setGender(gender);
           
            
        
            JOptionPane.showMessageDialog(this," Details have been updated.Click on display to check updated details."); 
        }
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnupdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount()>0){
            stamp=1;
        }
    }//GEN-LAST:event_btnupdateMousePressed

    private void txthouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthouseActionPerformed

    private void txtcommunityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcommunityKeyReleased
        // TODO add your handling code here:
        String SEQUENCE="^(ZIP 02215(Community 1)|ZIP 02115(Community 2))$";
        Pattern patt= Pattern.compile(SEQUENCE);
        Matcher match=patt.matcher(txtcommunity.getText());
        if(!match.matches()) {
            lblname.setText("Please check the entered data");
             btnupdate.setEnabled(false);
        }
         else{
            lblname.setText(null);
            btnupdate.setEnabled(true);
        }
    }//GEN-LAST:event_txtcommunityKeyReleased

    private void txthouseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthouseKeyReleased
        // TODO add your handling code here:
        
        String SEQUENCE="^[,a-zA-Z0-9 ]{0,30}$";
        Pattern patt= Pattern.compile(SEQUENCE);
        Matcher match=patt.matcher(txthouse.getText());
        if(!match.matches()) {
            lblname.setText("Please check the entered data");
             btnupdate.setEnabled(false);
        }
         else{
            lblname.setText(null);
            btnupdate.setEnabled(true);
        }
    }//GEN-LAST:event_txthouseKeyReleased

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        String SEQUENCE="^[0-9]{0,2}$";
        Pattern mat=Pattern.compile(SEQUENCE);
        Matcher match= mat.matcher(txtage.getText());
        if(!match.matches()) {
            lblmanuyr.setText("Please check the entered data");
            btnupdate.setEnabled(false);
        }
         else{
            lblmanuyr.setText(null);
            btnupdate.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtageKeyReleased

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tablecars.getModel();
       model.setRowCount(0);
       
       for(cars c : data.getData()){
           Object[] row = new Object[7];
           
           row[0] = c;
           row[1] = c.getName();
           row[2] = c.getAge();
           row[3] = c.getGender();
           row[4] = c.getHouse();
           row[5] = c.getCommunity();
           row[6] = c.getCity();
           
           model.addRow(row);
           
       }
        
    }
    private void txt_CITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CITYActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = tablecars.getSelectedRow();
        
        if (selectedRow<0){
            JOptionPane.showMessageDialog(this,"Select a row to view all details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)tablecars.getModel();
        cars selectedcars =(cars)model.getValueAt(selectedRow, 0);
        
        
        txtname.setText(selectedcars.getName());
        txthouse.setText(selectedcars.getHouse());
        txtpersonid.setText(selectedcars.getPersonID());
        txtcommunity.setText(selectedcars.getCommunity());
        txtage.setText(String.valueOf(selectedcars.getAge()));
        txtgender.setText(selectedcars.getGender());
        txt_CITY.setText(selectedcars.getCity());
        
//        SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
             
            
            //cars c=data.addNewcar();
            //txtname.setText(String.valueOf(selectedcars.getName()));
            //c.setName(txtname.getText());
//            txthouse.setText(String.valueOf(selectedcars.getHouse()));
//            txtage.setText(String.valueOf(selectedcars.getAge()));
//            txtcommunity.setText(String.valueOf(selectedcars.getCommunity()));
            //txtgender.setText(String.valueOf(selectedcars.getGender()));
            
            //txtgender.setText(String.valueOf(selectedcars.getGender()));
//            c.setAddress(txtaddress.getText());
//            c.setAge(age);
//            c.setLocation(community);
//            c.setGender(gender);
           
            
        
            //JOptionPane.showMessageDialog(this," Details have been updated.Click on display to check updated details."); 
    }//GEN-LAST:event_editbtnActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablecars.getSelectedRow();
        
        if (selectedRow<0){
            JOptionPane.showMessageDialog(this,"Select a row to view all details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)tablecars.getModel();
        cars selectedcars =(cars)model.getValueAt(selectedRow, 0);
        
        
        data.deletecars(selectedcars);
        populateTable();
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtpersonidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonidActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed
    private void txtmodelnameKeyReleased(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        
    }   
    private void txtmanufacturerKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        
        
    }                  
    private void txtyearKeyReleased(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:
        
                          
    }      
    private void txtseatsKeyReleased(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
       
    }    
       
    
          
         
         

         
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblavaila;
    private javax.swing.JLabel lblcolour;
    private javax.swing.JLabel lblloc;
    private javax.swing.JLabel lblmaintain;
    private javax.swing.JLabel lblmanu;
    private javax.swing.JLabel lblmanufacturer;
    private javax.swing.JLabel lblmanufactureryr;
    private javax.swing.JLabel lblmanuyr;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblplatee;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lblseatss;
    private javax.swing.JTable tablecars;
    private javax.swing.JTextField txt_CITY;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcommunity;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txthouse;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpersonid;
    // End of variables declaration//GEN-END:variables
}
